const HeaderDetailTypes = {
	UPDATE_HEADER_START: 'UPDATE_HEADER_START',
	UPDATE_HEADER_SUCCESS: 'UPDATE_HEADER_SUCCESS',
	UPDATE_HEADER_FAILURE: 'UPDATE_HEADER_FAILURE',

	FETCH_HEADER_START: 'FETCH_HEADER_START',
	FETCH_HEADER_SUCCESS: 'FETCH_HEADER_SUCCESS',
	FETCH_HEADER_FAILURE: 'FETCH_HEADER_FAILURE',

	SET_HEADER: 'SET_HEADER',

	EDIT_HEADER: 'EDIT_HEADER',

	CLEAR_HEADER: 'CLEAR_HEADER',
};

export default HeaderDetailTypes;
