const HeaderDetailTypes = {
	CREATE_HEADER_START: 'CREATE_HEADER_START',
	CREATE_HEADER_SUCCESS: 'CREATE_HEADER_SUCCESS',
	CREATE_HEADER_FAILURE: 'CREATE_HEADER_FAILURE',

	UPDATE_HEADER_START: 'UPDATE_HEADER_START',
	UPDATE_HEADER_SUCCESS: 'UPDATE_HEADER_SUCCESS',
	UPDATE_HEADER_FAILURE: 'UPDATE_HEADER_FAILURE',

	DELETE_HEADER_START: 'DELETE_HEADER_START',
	DELETE_HEADER_SUCCESS: 'DELETE_HEADER_SUCCESS',
	DELETE_HEADER_FAILURE: 'DELETE_HEADER_FAILURE',

	FETCH_HEADER_START: 'FETCH_HEADER_START',
	FETCH_HEADER_SUCCESS: 'FETCH_HEADER_SUCCESS',
	FETCH_HEADER_FAILURE: 'FETCH_HEADER_FAILURE',

	SET_HEADER: 'SET_HEADER',

	TOGGLE_EDIT: 'TOGGLE_EDIT',
};

export default HeaderDetailTypes;
