const TimeDetailTypes = {
	UPDATE_TIME_START: 'UPDATE_TIME_START',
	UPDATE_TIME_SUCCESS: 'UPDATE_TIME_SUCCESS',
	UPDATE_TIME_FAILURE: 'UPDATE_TIME_FAILURE',

	FETCH_TIME_START: 'FETCH_TIME_START',
	FETCH_TIME_SUCCESS: 'FETCH_TIME_SUCCESS',
	FETCH_TIME_FAILURE: 'FETCH_TIME_FAILURE',

	SET_TIME: 'SET_TIME',

	EDIT_TIME: 'EDIT_TIME',

	CLEAR_TIME: 'CLEAR_TIME',
};

export default TimeDetailTypes;
