const ServiceDetailTypes = {
	CREATE_SERVICE_START: 'CREATE_SERVICE_START',
	CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
	CREATE_SERVICE_FAILURE: 'CREATE_SERVICE_FAILURE',

	UPDATE_SERVICE_START: 'UPDATE_SERVICE_START',
	UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
	UPDATE_SERVICE_FAILURE: 'UPDATE_SERVICE_FAILURE',

	DELETE_SERVICE_START: 'DELETE_SERVICE_START',
	DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
	DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',

	FETCH_SERVICE_START: 'FETCH_SERVICE_START',
	FETCH_SERVICE_SUCCESS: 'FETCH_SERVICE_SUCCESS',
	FETCH_SERVICE_FAILURE: 'FETCH_SERVICE_FAILURE',

	SET_SERVICE: 'SET_SERVICE',

	EDIT_SERVICE: 'EDIT_SERVICE',

	CLEAR_SERVICE: 'CLEAR_SERVICE',
};

export default ServiceDetailTypes;
