const ServiceDetailTypes = {
	CREATE_SERVICES_START: 'CREATE_SERVICES_START',
	CREATE_SERVICES_SUCCESS: 'CREATE_SERVICES_SUCCESS',
	CREATE_SERVICES_FAILURE: 'CREATE_SERVICES_FAILURE',

	FETCH_SERVICE_START: 'FETCH_SERVICE_START',
	FETCH_SERVICE_SUCCESS: 'FETCH_SERVICE_SUCCESS',
	FETCH_SERVICE_FAILURE: 'FETCH_SERVICE_FAILURE',
};

export default ServiceDetailTypes;
