const ServiceDetailTypes = {
	CREATE_SERVICE_START: 'CREATE_SERVICE_START',
	CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
	CREATE_SERVICE_FAILURE: 'CREATE_SERVICE_FAILURE',

	UPDATE_SERVICE_START: 'UPDATE_SERVICE_START',
	UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
	UPDATE_SERVICE_FAILURE: 'UPDATE_SERVICE_FAILURE',

	DELETE_SERVICE_START: 'DELETE_SERVICE_START',
	DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
	DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',

	DELETE_MAIN_SERVICE_START: 'DELETE_MAIN_SERVICE_START',
	DELETE_MAIN_SERVICE_SUCCESS: 'DELETE_MAIN_SERVICE_SUCCESS',
	DELETE_MAIN_SERVICE_FAILURE: 'DELETE_MAIN_SERVICE_FAILURE',

	FETCH_SERVICE_START: 'FETCH_SERVICE_START',
	FETCH_SERVICE_SUCCESS: 'FETCH_SERVICE_SUCCESS',
	FETCH_SERVICE_FAILURE: 'FETCH_SERVICE_FAILURE',

	SET_SERVICE_START: 'SET_SERVICE_START',
	SET_SERVICE_SUCCESS: 'SET_SERVICE_SUCCESS',
	SET_SERVICE_FAILURE: 'SET_SERVICE_FAILURE',

	ADD_NEW_SERVICE_START: 'ADD_NEW_SERVICE_START',
	ADD_NEW_SERVICE_SUCCESS: 'ADD_NEW_SERVICE_SUCCESS',
	ADD_NEW_SERVICE_FAILURE: 'ADD_NEW_SERVICE_FAILURE',

	PUSH_NEW_SERVICE_START: 'PUSH_NEW_SERVICE_START',
	PUSH_NEW_SERVICE_SUCCESS: 'PUSH_NEW_SERVICE_SUCCESS',
	PUSH_NEW_SERVICE_FAILURE: 'PUSH_NEW_SERVICE_FAILURE',

	NEW_SERVICE_START: 'NEW_SERVICE_START',
	NEW_SERVICE_SUCCESS: 'NEW_SERVICE_SUCCESS',
	NEW_SERVICE_FAILURE: 'NEW_SERVICE_FAILURE',

	SET_NEW_SERVICE: 'SET_NEW_SERVICE',

	SET_OTHER_SERVICE: 'SET_OTHER_SERVICE',

	EDIT_SERVICE: 'EDIT_SERVICE',

	CLEAR_SERVICE: 'CLEAR_SERVICE',

	CLEAR_NEW_SERVICE: 'CLEAR_NEW_SERVICE',
};

export default ServiceDetailTypes;
