const ServicesActionTypes = {
	FETCH_SERVICES_COLLECTION_START: 'FETCH_SERVICES_COLLECTION_START',
	FETCH_SERVICES_COLLECTION_UPDATE: 'FETCH_SERVICES_COLLECTION_UPDATE',
	FETCH_SERVICES_COLLECTION_SUCCESS: 'FETCH_SERVICES_COLLECTION_SUCCESS',
	FETCH_SERVICES_COLLECTION_FAILURE: 'FETCH_SERVICES_COLLECTION_FAILURE',

	REMOVE_SERVICES_COLLECTION_LISTENER: 'REMOVE_SERVICES_COLLECTION_LISTENER',
};

export default ServicesActionTypes;
