const ContentActionTypes = {
	FETCH_CONTENT_COLLECTION_START: 'FETCH_CONTENT_COLLECTION_START',
	FETCH_CONTENT_COLLECTION_UPDATE: 'FETCH_CONTENT_COLLECTION_UPDATE',
	FETCH_CONTENT_COLLECTION_SUCCESS: 'FETCH_CONTENT_COLLECTION_SUCCESS',
	FETCH_CONTENT_COLLECTION_FAILURE: 'FETCH_CONTENT_COLLECTION_FAILURE',

	REMOVE_CONTENT_COLLECTION_LISTENER: 'REMOVE_CONTENT_COLLECTION_LISTENER',
};

export default ContentActionTypes;
