const AboutUsDetailTypes = {
	CREATE_ABOUT_US_START: 'CREATE_ABOUT_US_START',
	CREATE_ABOUT_US_SUCCESS: 'CREATE_ABOUT_US_SUCCESS',
	CREATE_ABOUT_US_FAILURE: 'CREATE_ABOUT_US_FAILURE',

	UPDATE_ABOUT_US_START: 'UPDATE_ABOUT_US_START',
	UPDATE_ABOUT_US_SUCCESS: 'UPDATE_ABOUT_US_SUCCESS',
	UPDATE_ABOUT_US_FAILURE: 'UPDATE_ABOUT_US_FAILURE',

	DELETE_ABOUT_US_START: 'DELETE_ABOUT_US_START',
	DELETE_ABOUT_US_SUCCESS: 'DELETE_ABOUT_US_SUCCESS',
	DELETE_ABOUT_US_FAILURE: 'DELETE_ABOUT_US_FAILURE',

	FETCH_ABOUT_US_START: 'FETCH_ABOUT_US_START',
	FETCH_ABOUT_US_SUCCESS: 'FETCH_ABOUT_US_SUCCESS',
	FETCH_ABOUT_US_FAILURE: 'FETCH_ABOUT_US_FAILURE',

	SET_ABOUT_US: 'SET_ABOUT_US',

	EDIT_ABOUT_US: 'EDIT_ABOUT_US',

	CLEAR_ABOUT_US: 'CLEAR_ABOUT_US',
};

export default AboutUsDetailTypes;
