const AboutUsDetailTypes = {
	UPDATE_ABOUT_US_START: 'UPDATE_ABOUT_US_START',
	UPDATE_ABOUT_US_SUCCESS: 'UPDATE_ABOUT_US_SUCCESS',
	UPDATE_ABOUT_US_FAILURE: 'UPDATE_ABOUT_US_FAILURE',

	FETCH_ABOUT_US_START: 'FETCH_ABOUT_US_START',
	FETCH_ABOUT_US_SUCCESS: 'FETCH_ABOUT_US_SUCCESS',
	FETCH_ABOUT_US_FAILURE: 'FETCH_ABOUT_US_FAILURE',

	SET_ABOUT_US: 'SET_ABOUT_US',

	EDIT_ABOUT_US: 'EDIT_ABOUT_US',

	CLEAR_ABOUT_US: 'CLEAR_ABOUT_US',
};

export default AboutUsDetailTypes;
