const UserActionTypes = {
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
	EMAIL_SIGN_IN_FAILURE: 'EMAIL_SIGN_IN_FAILURE',

	SET_LOGIN_CREDENTIALS: 'SET_LOGIN_CREDENTIALS',

	CLEAR_LOGIN_CREDENTIALS: 'CLEAR_LOGIN_CREDENTIALS',

	LOG_OUT: 'LOG_OUT',
};

export default UserActionTypes;
