const FooterDetailTypes = {
	UPDATE_FOOTER_START: 'UPDATE_FOOTER_START',
	UPDATE_FOOTER_SUCCESS: 'UPDATE_FOOTER_SUCCESS',
	UPDATE_FOOTER_FAILURE: 'UPDATE_FOOTER_FAILURE',

	FETCH_FOOTER_START: 'FETCH_FOOTER_START',
	FETCH_FOOTER_SUCCESS: 'FETCH_FOOTER_SUCCESS',
	FETCH_FOOTER_FAILURE: 'FETCH_FOOTER_FAILURE',

	SET_FOOTER: 'SET_FOOTER',

	EDIT_FOOTER: 'EDIT_FOOTER',

	CLEAR_FOOTER: 'CLEAR_FOOTER',
};

export default FooterDetailTypes;
